syntax = "proto3";

package nlg.socialmedia.v1;

import "amino/amino.proto";
import "gogoproto/gogo.proto";
import "nlg/socialmedia/v1/comment.proto";
import "nlg/socialmedia/v1/params.proto";
import "nlg/socialmedia/v1/post.proto";
import "nlg/socialmedia/v1/profile.proto";

option go_package = "nlg/x/socialmedia/types";

// GenesisState defines the socialmedia module's genesis state.
message GenesisState {
  // params defines all the parameters of the module.
  Params params = 1 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
  repeated Post post_map = 2 [(gogoproto.nullable) = false];
  repeated Profile profile_map = 3 [(gogoproto.nullable) = false];
  repeated Comment comment_map = 4 [(gogoproto.nullable) = false];
}
