// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nlg/socialmedia/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the socialmedia module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params              Params             `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	PostMap             []Post             `protobuf:"bytes,2,rep,name=post_map,json=postMap,proto3" json:"post_map"`
	ProfileMap          []Profile          `protobuf:"bytes,3,rep,name=profile_map,json=profileMap,proto3" json:"profile_map"`
	CommentMap          []Comment          `protobuf:"bytes,4,rep,name=comment_map,json=commentMap,proto3" json:"comment_map"`
	SocialConnectionMap []SocialConnection `protobuf:"bytes,5,rep,name=social_connection_map,json=socialConnectionMap,proto3" json:"social_connection_map"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2099fc3657412c7, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetPostMap() []Post {
	if m != nil {
		return m.PostMap
	}
	return nil
}

func (m *GenesisState) GetProfileMap() []Profile {
	if m != nil {
		return m.ProfileMap
	}
	return nil
}

func (m *GenesisState) GetCommentMap() []Comment {
	if m != nil {
		return m.CommentMap
	}
	return nil
}

func (m *GenesisState) GetSocialConnectionMap() []SocialConnection {
	if m != nil {
		return m.SocialConnectionMap
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "nlg.socialmedia.v1.GenesisState")
}

func init() { proto.RegisterFile("nlg/socialmedia/v1/genesis.proto", fileDescriptor_b2099fc3657412c7) }

var fileDescriptor_b2099fc3657412c7 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x31, 0x4e, 0xc3, 0x30,
	0x14, 0x86, 0x93, 0xb6, 0x14, 0x70, 0x59, 0x08, 0x20, 0xaa, 0x20, 0xd2, 0x0a, 0x31, 0x54, 0x1d,
	0x12, 0xb5, 0x4c, 0x0c, 0x2c, 0xe9, 0xc0, 0x54, 0x09, 0xb5, 0x1b, 0x03, 0x95, 0x09, 0x26, 0x8a,
	0x94, 0xd8, 0x56, 0x6d, 0x55, 0x70, 0x0b, 0x8e, 0xc1, 0xc8, 0x31, 0x3a, 0x76, 0x64, 0x42, 0xa8,
	0x19, 0x58, 0x39, 0x02, 0xb2, 0xfd, 0x40, 0x40, 0x0d, 0x8b, 0x65, 0x5b, 0xdf, 0xff, 0xd9, 0xef,
	0x3d, 0xd4, 0xa6, 0x79, 0x1a, 0x09, 0x96, 0x64, 0x38, 0x2f, 0xc8, 0x4d, 0x86, 0xa3, 0x59, 0x2f,
	0x4a, 0x09, 0x25, 0x22, 0x13, 0x21, 0x9f, 0x32, 0xc9, 0x3c, 0x8f, 0xe6, 0x69, 0xf8, 0x8d, 0x08,
	0x67, 0x3d, 0x7f, 0x1b, 0x17, 0x19, 0x65, 0x91, 0x5e, 0x0d, 0xe6, 0xef, 0xa6, 0x2c, 0x65, 0x7a,
	0x1b, 0xa9, 0x1d, 0xdc, 0xda, 0xf4, 0x09, 0x2b, 0x0a, 0x42, 0x25, 0x10, 0x2d, 0x0b, 0xc1, 0xf1,
	0x14, 0x17, 0xf0, 0xbe, 0x7f, 0x68, 0x03, 0x98, 0x90, 0xff, 0xbc, 0xc0, 0xa7, 0xec, 0x36, 0xcb,
	0x09, 0x10, 0x5d, 0x0b, 0x61, 0x8e, 0x93, 0x84, 0x51, 0x4a, 0x12, 0x99, 0x31, 0x6a, 0xd8, 0xa3,
	0xf7, 0x0a, 0xda, 0x3a, 0x37, 0xe5, 0x8f, 0x25, 0x96, 0xc4, 0x3b, 0x43, 0x75, 0xf3, 0x9b, 0xa6,
	0xdb, 0x76, 0x3b, 0x8d, 0xbe, 0x1f, 0xae, 0xb6, 0x23, 0xbc, 0xd0, 0x44, 0xbc, 0x39, 0x7f, 0x69,
	0x39, 0x8f, 0x6f, 0x4f, 0x5d, 0x77, 0x04, 0x21, 0xef, 0x14, 0x6d, 0xa8, 0xbf, 0x4e, 0x0a, 0xcc,
	0x9b, 0x95, 0x76, 0xb5, 0xd3, 0xe8, 0x37, 0xad, 0x02, 0x26, 0x64, 0x5c, 0x53, 0xf1, 0xd1, 0xba,
	0xe2, 0x87, 0x98, 0x7b, 0x31, 0x6a, 0x40, 0x1d, 0x3a, 0x5d, 0xd5, 0xe9, 0x03, 0x6b, 0xda, 0x60,
	0x20, 0x40, 0x90, 0x02, 0x07, 0x74, 0x5b, 0x3b, 0x6a, 0x7f, 0x3b, 0x06, 0x06, 0xfb, 0x74, 0x40,
	0x4a, 0x39, 0xae, 0xd0, 0xde, 0x4a, 0xb7, 0xb4, 0x6d, 0x4d, 0xdb, 0x8e, 0x6d, 0xb6, 0xb1, 0x3e,
	0x0e, 0xbe, 0x78, 0xd0, 0xee, 0x88, 0x5f, 0xf7, 0x43, 0xcc, 0xe3, 0xde, 0x7c, 0x19, 0xb8, 0x8b,
	0x65, 0xe0, 0xbe, 0x2e, 0x03, 0xf7, 0xa1, 0x0c, 0x9c, 0x45, 0x19, 0x38, 0xcf, 0x65, 0xe0, 0x5c,
	0xee, 0xab, 0xc1, 0xdd, 0xfd, 0x18, 0x9d, 0xbc, 0xe7, 0x44, 0x5c, 0xd7, 0xf5, 0xb0, 0x4e, 0x3e,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x99, 0xc2, 0x3a, 0xbd, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SocialConnectionMap) > 0 {
		for iNdEx := len(m.SocialConnectionMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SocialConnectionMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.CommentMap) > 0 {
		for iNdEx := len(m.CommentMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CommentMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.ProfileMap) > 0 {
		for iNdEx := len(m.ProfileMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ProfileMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.PostMap) > 0 {
		for iNdEx := len(m.PostMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PostMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.PostMap) > 0 {
		for _, e := range m.PostMap {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ProfileMap) > 0 {
		for _, e := range m.ProfileMap {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.CommentMap) > 0 {
		for _, e := range m.CommentMap {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SocialConnectionMap) > 0 {
		for _, e := range m.SocialConnectionMap {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PostMap = append(m.PostMap, Post{})
			if err := m.PostMap[len(m.PostMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProfileMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProfileMap = append(m.ProfileMap, Profile{})
			if err := m.ProfileMap[len(m.ProfileMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommentMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommentMap = append(m.CommentMap, Comment{})
			if err := m.CommentMap[len(m.CommentMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SocialConnectionMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SocialConnectionMap = append(m.SocialConnectionMap, SocialConnection{})
			if err := m.SocialConnectionMap[len(m.SocialConnectionMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
